common:
    resource: "@CommonBundle/Controller/"
    type:     annotation
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard1

listener:
    resource: "@DashboardBundle/Controller/HandlerController.php"
    type:     annotation
    prefix:   /handler

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /dashboard/user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_core:
    resource: "@AppCoreBundle/Presentation/Controllers/"
    type:     annotation
    prefix:   /dashboard

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
