dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
